AWSTemplateFormatVersion: 2010-09-09

Description: M1 API Stack

Resources:

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
      - email
  
  UserPoolClient:  
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: m1-api-user-pool-client
      UserPoolId: !Ref UserPool
      
  APIGatewayVPCLink:
    Type: AWS::ApiGateway::VpcLink
    Properties: 
      Name: m1-api-vpc-link
      TargetArns: 
      - !ImportValue m1-core-stack:CoreLoadBalancer
      
      
  API:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: m1-api
      Body: 
        
        swagger: 2.0
        info:
          title: m1-api
        securityDefinitions:
          m1-user-pool-authorizer:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              type: COGNITO_USER_POOLS
              providerARNs:
              - !Sub arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}
        
        paths:
          /:
            # x-amazon-apigateway-any-method:
            #     parameters:
            #     - name: "proxy"
            #       in: "path"
            #       required: true
            #       type: "string"
            #     responses:
            #       "200"

            get:
              responses:
                "200":
                  description: Default response for CORS method
                  headers:
                    Access-Control-Allow-Headers:
                      type: string
                    Access-Control-Allow-Methods:
                      type: string
                    Access-Control-Allow-Origin:
                      type: string
                      
              x-amazon-apigateway-integration:
                connectionType: VPC_LINK
                responses: 
                  default:
                    statusCode: 200
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
                      method.response.header.Access-Control-Allow-Methods: "'*'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
                connectionId: !Ref APIGatewayVPCLink
                httpMethod: GET
                type: HTTP_PROXY
                uri: http://m1-core-nlb-97744d9745ff1c16.elb.us-east-1.amazonaws.com/
                
                
      EndpointConfiguration: 
        Types: 
        - REGIONAL
      FailOnWarnings: true

# Outputs:

Outputs:

#   Region:
#     Value: !Ref AWS::Region
#     Export:
#       Name: !Sub ${AWS::StackName}:Region
      
 
   Test:
     Description: Test
     Value: !Ref APIGatewayVPCLink
     Export:
       Name: Test