---
AWSTemplateFormatVersion: '2010-09-09'

Description: M1 Project test stack updated

Mappings:

  SubnetConfig:
    VPC:
      CIDR: '10.0.0.0/16'
    PublicOne:
      CIDR: '10.0.0.0/24'
    PublicTwo:
      CIDR: '10.0.1.0/24'
    PrivateOne:
      CIDR: '10.0.2.0/24'
    PrivateTwo:
      CIDR: '10.0.3.0/24'
      
Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      Tags:
      - Key: "Name"
        Value: "m1-core-vpc"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !FindInMap ['SubnetConfig', 'VPC', 'CIDR']

Outputs:

  VPCId:
    Description: M1 Core VPC
    Value: !Ref 'VPC'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'VPCId' ] ]