# dictConfig({
#     'version': 1,
#     'formatters': {'default': {
#         'format': '%(module)6.6s | %(levelname).4s | %(message)s',
#         # 'format': '[%(asctime)s] %(module)6.6s | %(levelname).4s | %(message)s', 
#         # 'datefmt': "%Y-%m-%d %H:%M:%S",
#     }},
#     'handlers': {'wsgi': {
#         'class': 'logging.StreamHandler',
#         'stream': 'ext://flask.logging.wsgi_errors_stream',
#         'formatter': 'default'
#     }},
#     'root': {
#         'level': 'INFO',
#         'handlers': ['wsgi']
#     }
# })

version: 1

formatters:
  default:
    format: '%(module)6.6s | %(levelname).4s | %(message)s'
  # full:
  #   format: '[%(asctime)s] %(module)6.6s | %(levelname).4s | %(message)s'
  #   datefmt: "%Y-%m-%d %H:%M:%S"
    
handlers:
  wsgi:
    class: logging.StreamHandler
    stream: ext://flask.logging.wsgi_errors_stream
    formatter: default
    
root:
  level: INFO
  handlers: [wsgi]