version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Retrieves docker credentials so that the subsequent docker push command is
      # authorized. Authentication is performed automatically by the AWS CLI
      # using the AWS credentials associated with the IAM role assigned to the
      # instances in your AWS CodeBuild project.
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      
      # - echo GET CALLER IDENTITY
      # - aws sts get-caller-identity

      # - mkdir ~/.aws/ && touch ~/.aws/config
      # - echo "[default]" > ~/.aws/config
      # - echo "region=us-east-1" >> ~/.aws/config
      # - echo "role_arn=arn:aws:iam::196332284574:role/m1-ecs-task-role" >> ~/.aws/config
      # - echo "credential_source=EcsContainer" >> ~/.aws/config
      # - cat ~/.aws/config
      # - env
      
      # - touch ~/.aws/credentials
      # - echo "[default]" > ~/.aws/credentials
      # - echo "region=us-east-1" >> ~/.aws/credentials
      # - echo "role_arn=arn:aws:iam::196332284574:role/m1-ecs-task-role" >> ~/.aws/credentials
      # - echo "credential_source=EcsContainer" >> ~/.aws/credentials
      # - cat ~/.aws/credentials
      # - env
      
      - docker build -t m1-core-image:latest .
      - docker tag m1-core-image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/m1-core-image:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image..

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/m1-core-image:latest
      - echo Completed pushing Docker image on `date`

      # Artifacts file with ECR image name and location
      - printf '[{"name":"m1-core-image","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/m1-core-image:latest > m1-core-image-definitions.json

artifacts:

  files: m1-core-image-definitions.json
